### ISSUE TITLE
Which carriers are supported already?

### ISSUE THREAD

**Issue by gelsas** [parcelmaster/parcelmaster-frontend#16]
Which carriers are supported already?

**Comment by benjamin-hempel** [comment]
Hi gelsas,

the app is still in very early stages of development. I'm currently working on setting up infrastructure. The first carriers I'm planning to support are from DPDHL group since they have a unified API. As I'm from Germany, I will focus on German carriers first and will then probably move on to major European and American ones.

Best regards
Benjamin

**Comment by benjamin-hempel** [comment]
I'll close this for now since I'll probably do a list of supported carriers once the app has reached a presentable state. If you have any further questions feel free to open another issue. Thank you!
